// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3qLwscdd9vFDfXcl3Vp9OkyBOz5-SytE',
    appId: '1:752488511015:web:cfd986882199c87e1c4002',
    messagingSenderId: '752488511015',
    projectId: 'eleonoravisnevskyte',
    authDomain: 'eleonoravisnevskyte.firebaseapp.com',
    storageBucket: 'eleonoravisnevskyte.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCX-jZAE93plTY2N6olzyUVKjYaT44Y9hI',
    appId: '1:752488511015:android:121088fdfa6e7e871c4002',
    messagingSenderId: '752488511015',
    projectId: 'eleonoravisnevskyte',
    storageBucket: 'eleonoravisnevskyte.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxvDvxGWWHIyOSR7N6PGS1mA2G1wCOgp8',
    appId: '1:752488511015:ios:fc07652e3c8692e91c4002',
    messagingSenderId: '752488511015',
    projectId: 'eleonoravisnevskyte',
    storageBucket: 'eleonoravisnevskyte.firebasestorage.app',
    iosBundleId: 'com.example.runfree',
  );
}
